version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - temp:/app/tmp
    environment:
      - ID
      - TOKEN
      - URL
      - DATABASE_URL
    ports:
      - 8810:3000
volumes:
  temp:
